"""Dispatch table for the Confluence storage-format converter.

Importing this module registers every plain-HTML and rd-* handler with
`converter.HANDLERS`. Mirrors the layout used by the md / docx exporters
so the three pipelines share a recognisable shape.
"""

from __future__ import annotations

from . import handlers_plain as p
from . import handlers_rd as r
from .converter import HANDLERS


HANDLERS.update({
    # plain HTML
    "h1": p._h_h(1),
    "h2": p._h_h(2),
    "h3": p._h_h(3),
    "h4": p._h_h(4),
    "h5": p._h_h(5),
    "h6": p._h_h(6),
    "p": p._h_p,
    "br": p._h_br,
    "hr": p._h_hr,
    "strong": p._h_strong,
    "b": p._h_strong,
    "em": p._h_em,
    "i": p._h_em,
    "s": p._h_s,
    "del": p._h_s,
    "strike": p._h_s,
    "sup": p._h_sup,
    "sub": p._h_sub,
    "code": p._h_code_inline,
    "pre": p._h_pre,
    "blockquote": p._h_blockquote,
    "a": p._h_a,
    "img": p._h_img,
    "ul": p._h_list("ul"),
    "ol": p._h_list("ol"),
    "li": p._h_li,
    "table": p._h_table,
    "thead": p._h_unwrap,
    "tbody": p._h_unwrap,
    "tfoot": p._h_unwrap,
    "tr": p._h_unwrap,
    "th": p._h_unwrap,
    "td": p._h_unwrap,
    "div": p._h_unwrap,
    "span": p._h_unwrap,
    "section": p._h_unwrap,
    "article": p._h_unwrap,
    "header": p._h_unwrap,
    "footer": p._h_unwrap,
    "main": p._h_unwrap,
    "nav": p._h_unwrap,
    "aside": p._h_unwrap,
    "figure": p._h_figure,
    "figcaption": p._h_em,
    "time": p._h_unwrap,
    "small": p._h_unwrap,
    "u": p._h_unwrap,
    "mark": p._h_unwrap,
    # head / metadata
    "script": p._h_drop,
    "style": p._h_drop,
    "head": p._h_drop,
    "meta": p._h_drop,
    "title": p._h_drop,
    "link": p._h_drop,
    # rd-*
    "rd-page": r._h_rd_page,
    "rd-banner": r._h_rd_banner,
    "rd-hero": r._h_rd_hero,
    "rd-section": r._h_rd_section,
    "rd-callout": r._h_rd_callout,
    "rd-cols": r._h_rd_cols,
    "rd-card": r._h_rd_card,
    "rd-kv": r._h_rd_kv,
    "rd-row": r._h_rd_row,
    "rd-badge": r._h_rd_badge,
    "rd-stat": r._h_rd_stat,
    "rd-progress": r._h_rd_progress,
    "rd-update": r._h_rd_update,
    "rd-compare": r._h_rd_compare,
    "rd-rubric": r._h_rd_rubric,
    "rd-code": r._h_rd_code,
    "rd-diff": r._h_rd_diff,
    "rd-shell": r._h_rd_shell,
    "rd-math": r._h_rd_math,
    "rd-figure": r._h_rd_figure,
    "rd-chart": r._h_rd_chart,
    "rd-tabs": r._h_rd_tabs,
    "rd-timeline": r._h_rd_timeline,
    "rd-steps": r._h_rd_steps,
    "rd-detail": r._h_rd_detail,
    "rd-checklist": r._h_rd_checklist,
    "rd-diagram": r._h_rd_diagram,
    "rd-toc": r._h_rd_toc,
    "rd-icon": r._h_rd_icon,
    "rd-decision": r._h_rd_decision,
    "rd-pros-cons": r._h_rd_pros_cons,
    "rd-api": r._h_rd_api,
    "rd-references": r._h_rd_references,
    "rd-ref": r._h_rd_ref,
    "rd-cite": r._h_rd_cite,
})
